sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.4
      env: 'COMPOSER_PHPUNIT="lowest"'

before_script:
  - "composer install --prefer-dist"
  - if [ "$COMPOSER_PHPUNIT" = "lowest" ]; then composer update --prefer-lowest --with-dependencies phpunit/phpunit; fi;

script:
  # Standard build script
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]] ; then vendor/bin/phing test; fi
  # HHVM script (phing not currently supported on hhvm pending http://www.phing.info/trac/ticket/1086)
  - if [[ $TRAVIS_PHP_VERSION == "hhvm" ]] ; then ./vendor/bin/phpunit --bootstrap=vendor/kohana/unittest/bootstrap_all_modules.php vendor/kohana/unittest/tests.php ; fi

notifications:
  irc:
    channels:
      - "irc.freenode.org#kohana"
    template:
      - "%{repository}/%{branch} (%{commit}) - %{author}: %{message}"
      - "Build details: %{build_url}"
  email: false
